import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import { ReactNode } from "react";
import ModalProvider from "./context/ModalProvider";
import AppModal from "../components/AppModal";
import Footer from "../components/Footer"
import { Toaster } from "react-hot-toast";
import { AuthInitializer } from "../lib/AuthProvider"



// Import Inter
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased `}>
        <AuthInitializer>
          <ModalProvider>
            <NavBar />
            <AppModal />
            <main>
              {children}
              <Toaster position="top-right" />
            </main>
            <Footer />
          </ModalProvider>
        </AuthInitializer>
      </body>
    </html>
  );
}
